<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>protocols-balanced</artifactId>
        <groupId>edu.alibaba</groupId>
        <version>1.1.5</version>
            <relativePath>../pom.xml</relativePath>
</parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>mpc4j-psu-protocol-gmr21</artifactId>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-psu-common</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-common-rpc</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-common-tool</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>libpsu-spi</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-s2pc-pcg</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-s2pc-opf</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-psu-plugin-cot</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-psu-plugin-mqrpmt</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-psu-core</artifactId>
            <version>1.1.5</version>
        </dependency>
        <dependency>
            <groupId>edu.alibaba</groupId>
            <artifactId>mpc4j-psu-api</artifactId>
            <version>1.1.5</version>
        </dependency>
    </dependencies>
</project>
