# Fair benchmark (2^8 = 256 x 256).

server_name = server
server_ip = 127.0.0.1
server_port = 19018

client_name = client
client_ip = 127.0.0.1
client_port = 19019

append_string = fair_bench_2p8

pto_type = PSU

# 128-bit items
element_byte_length = 16
server_log_set_size = 8
client_log_set_size = 8
parallel = true
skip_warmup = true
skip_gc = true

psu_pto_name = USENIX:YanShiHonDaw24

jszg24_item_bit_length = 128
jszg24_lambda = 40
jszg24_gamma = 3
jszg24_epsilon = 1.27
jszg24_max_cuckoo_retry = 40

silent_cot = true

