# Fair benchmark (2^6 = 64 x 64).

server_name = server
server_ip = 127.0.0.1
server_port = 19019

client_name = client
client_ip = 127.0.0.1
client_port = 19020

append_string = fair_bench_2p6

pto_type = PSI

element_byte_length = 16
server_log_set_size = 6
client_log_set_size = 6
parallel = true
skip_warmup = true
skip_gc = true

psi_pto_name = JOC:HazNis12
