# Fair benchmark (2^4 = 16 x 16).

server_name = server
server_ip = 127.0.0.1
server_port = 19002

client_name = client
client_ip = 127.0.0.1
client_port = 19003

append_string = fair_bench_2p4

pto_type = PSU

element_byte_length = 16
server_log_set_size = 4
client_log_set_size = 4
parallel = true
skip_warmup = true
skip_gc = true

psu_pto_name = PKC:CheZhaZha24

silent_cot = true
compress_encode = true
rosn_type = PKC:GMRSS21_NET
