<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>mpc4j-psu</artifactId>
        <groupId>edu.alibaba</groupId>
        <version>1.1.5</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <artifactId>mpc4j-psu-bom</artifactId>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>libpsu-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>libpsu-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>libpsu-spi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>libpsu-factory</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>libpsu-test-fixtures</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-balanced</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-balanced-spi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-unbalanced</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-unbalanced-spi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-psi-spi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-psi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-ks05</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-hn12</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-ba12</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-krtw19</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-gmr21</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-jsz22</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-zcl23</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-czz24</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-css25</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-pt26</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-dc17</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-f07</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-tbz25</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-haowan2026</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-jszg24</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-pgt26</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-small-ec-elligator-psu</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-tcl23</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-protocol-tbz25-upsu</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-plugin-cot</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-plugin-mqrpmt</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>mpc4j-psu-plugin-ccpsi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.alibaba</groupId>
                <artifactId>libpsu-plugin-aon-output</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
