# Fair benchmark (2^16 = 65536 x 65536).

server_name = server
server_ip = 127.0.0.1
server_port = 19019

client_name = client
client_ip = 127.0.0.1
client_port = 19020

append_string = fair_bench_2p16

pto_type = PSU

element_byte_length = 16
server_log_set_size = 16
client_log_set_size = 16
parallel = true
skip_warmup = true
skip_gc = true

psu_pto_name = JOC:HazNis12
