# Fair UPSU: sender 2^10 = 1024, receiver 2^20 = 1048576.
# server = sender (X), client = receiver (Y).

server_name = server
server_ip = 127.0.0.1
server_port = 19202

client_name = client
client_ip = 127.0.0.1
client_port = 19203

append_string = fair_bench_unbalanced_2p10x2p20

pto_type = UPSU

element_byte_length = 16
server_log_set_size = 10
client_log_set_size = 20
parallel = true
skip_warmup = true
skip_gc = true

upsu_pto_name = USENIX:BinYujConYanYu25

silent_cot = true
