# Fair benchmark (2^10 = 1024 x 1024).

server_name = server
server_ip = 127.0.0.1
server_port = 19102

client_name = client
client_ip = 127.0.0.1
client_port = 19103

append_string = fair_bench_2p10

pto_type = PSU

element_byte_length = 16
server_log_set_size = 10
client_log_set_size = 10
parallel = true
skip_warmup = true
skip_gc = true

psu_pto_name = USENIX:BinYujConYanYu25

silent_cot = true
