# Fair benchmark (2^12 = 4096 x 4096).
server_name = server
server_ip = 127.0.0.1
server_port = 19006

client_name = client
client_ip = 127.0.0.1
client_port = 19007

append_string = fair_bench_2p12

pto_type = PSU
element_byte_length = 16
server_log_set_size = 12
client_log_set_size = 12
parallel = true

psu_pto_name = EUROCRYPT:PuGaoTri26
pgt26_2m_skip_shuffle_proof = false
pgt26_2m_skip_rddh_proof = false
skip_warmup = true
skip_gc = true
silent_cot = true
