# Fair benchmark (2^5 = 32 x 32).

server_name = server
server_ip = 127.0.0.1
server_port = 19206

client_name = client
client_ip = 127.0.0.1
client_port = 19207

append_string = fair_bench_2p5

pto_type = PSU

element_byte_length = 16
server_log_set_size = 5
client_log_set_size = 5
parallel = true
skip_warmup = true
skip_gc = true

psu_pto_name = Ours
small_ec_item_bit_length = 128
small_ec_log_stats = true
