<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>protocols</artifactId>
        <groupId>edu.alibaba</groupId>
        <version>1.1.5</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>protocols-unbalanced</artifactId>
    <packaging>pom</packaging>
    <name>libPSU unbalanced UPSU protocols</name>
    <modules>
        <module>tcl23</module>
        <module>tbz25</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>--add-modules=jdk.incubator.vector -Djava.library.path=${env.MPC4J_NATIVE_TOOL_DIR}:${project.basedir}/../../../../mpc4j-native-tool/cmake-build-release:${env.MPC4J_NATIVE_FHE_DIR}:${project.basedir}/../../../../mpc4j-native-fhe/cmake-build-release</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
