package edu.alibaba.mpc4j.s2pc.ba12;

/**
 * BA12 set / cardinality operations exposed to the driver.
 */
public enum Ba12Operation {
    BA12_UNION,
    BA12_INTERSECTION,
    BA12_DIFFERENCE,
    BA12_SYMMETRIC_DIFFERENCE,
    BA12_SUBSET,
    BA12_SUPERSET,
    BA12_EQUALITY,
    BA12_ELEMENT_REDUCTION,
    BA12_UNION_CARDINALITY,
    BA12_INTERSECTION_CARDINALITY,
    BA12_DIFFERENCE_CARDINALITY,
    BA12_SYMMETRIC_DIFFERENCE_CARDINALITY,
    BA12_ELEMENT_REDUCTION_CARDINALITY,
}
